export type Locale = "en" | "ja" | "es";
export type Copy = Record<Locale, string>;
export const copy = {
  dashboard: { en: "Dashboard", ja: "ダッシュボード", es: "Panel" },
  workspace: { en: "Workspace", ja: "分析デスク", es: "Mesa de trabajo" },
  players: { en: "Players", ja: "選手", es: "Jugadores" },
  teams: { en: "Teams", ja: "クラブ", es: "Equipos" },
  analytics: { en: "Analytics", ja: "分析", es: "Análisis" },
  qa: { en: "Data checks", ja: "データ確認", es: "Revisión de datos" },
  reports: { en: "Reports", ja: "レポート", es: "Reportes" },
  import: { en: "Import CSV", ja: "CSVを取り込む", es: "Importar CSV" },
  compare: { en: "Compare forwards", ja: "FWを比較", es: "Comparar delanteros" },
  proof: { en: "Portfolio evidence", ja: "制作事例", es: "Muestras del portafolio" },
  download: { en: "Download", ja: "ダウンロード", es: "Descargar" },
  search: { en: "Search", ja: "検索", es: "Buscar" },
  all: { en: "All", ja: "すべて", es: "Todos" },
  source: { en: "Source", ja: "出典", es: "Fuente" },
  date: { en: "Imported", ja: "取り込み日", es: "Fecha de importación" },
  club: { en: "Club", ja: "所属クラブ", es: "Club" },
  league: { en: "League", ja: "リーグ", es: "Liga" },
  country: { en: "Country", ja: "国", es: "País" },
  position: { en: "Position", ja: "ポジション", es: "Posición" },
  shots: { en: "Shots", ja: "シュート", es: "Remates" },
  goals: { en: "Goals", ja: "得点", es: "Goles" },
  minutes: { en: "Minutes", ja: "出場時間", es: "Minutos" },
  empty: { en: "No records match these filters.", ja: "条件に一致するデータはありません。", es: "No hay registros que coincidan con estos filtros." },
  rosterNote: { en: "Imported roster claims need a club-source review. Counts describe our records, not a complete squad.", ja: "所属情報はクラブの公式情報との照合が必要です。件数は取り込んだデータ数で、全選手数ではありません。", es: "La información de los planteles necesita revisión con fuentes del club. El conteo corresponde a nuestros registros, no al plantel completo." },
  compareNote: { en: "Copa América 2024 · StatsBomb Open Data. This tournament sample does not rank today's best forwards. Small samples and penalties affect comparisons.", ja: "コパ・アメリカ2024のStatsBomb公開データを使用しています。現在のFWランキングではありません。試合数やPKの有無によって比較結果は変わります。", es: "Copa América 2024 · StatsBomb Open Data. Esta muestra del torneo no clasifica a los mejores delanteros actuales. El tamaño de la muestra y los penales influyen en la comparación." },
} satisfies Record<string, Copy>;
export function isLocale(value: unknown): value is Locale { return value === "en" || value === "ja" || value === "es"; }
export const pageTitles: Record<string, Copy> = {
  "/": { en: "Football research, checked before it becomes a report.", ja: "サッカーのデータを確認し、レポートにつなげる。", es: "Datos de fútbol revisados antes de convertirlos en un reporte." },
  "/players": copy.players,
  "/qa": { en: "Data check report", ja: "データ確認レポート", es: "Reporte de revisión de datos" },
  "/analytics": { en: "Shot quality for South American forwards.", ja: "南米のFWのシュートを分析する。", es: "Calidad de remate de delanteros sudamericanos." },
  "/analytics/forwards": { en: "Compare how forwards find their shots.", ja: "FWのシュート位置と質を比較する。", es: "Compará dónde y cómo rematan los delanteros." },
  "/analytics/champions": { en: "Champions League ETL demo.", ja: "チャンピオンズリーグのデータ取り込み事例。", es: "Importación de datos de la Champions League." },
  "/reports": { en: "Write the report, then show the checks.", ja: "レポートと確認内容を一緒に残す。", es: "El reporte, con sus revisiones a la vista." },
  "/proof/before-after": { en: "Before and after, with the checks left visible.", ja: "修正前と修正後を、確認理由と一緒に。", es: "Antes y después, con los motivos de cada corrección." },
  "/workspace": { en: "The control room for ScoutBoard AI.", ja: "ScoutBoard AIの分析デスク。", es: "La mesa de trabajo de ScoutBoard AI." },
  "/workspace/data-readiness": { en: "Every provider has a job, a rule, and a limit.", ja: "データ提供元ごとの用途、条件、制限を確認する。", es: "Qué aporta cada fuente y cuáles son sus límites." },
  "/workspace/league-coverage": { en: "League coverage before player search.", ja: "選手を探す前にリーグの収録状況を確認する。", es: "Revisá la cobertura de las ligas antes de buscar jugadores." },
  "/workspace/tasks": { en: "Turn data gaps into visible work.", ja: "不足しているデータを確認タスクにする。", es: "Convertí los datos faltantes en tareas de revisión." },
  "/workspace/video-tracking": { en: "Tracking data adapter", ja: "トラッキングデータの取り込み", es: "Integración de datos de seguimiento" },
  "/players/watchlist": { en: "Find the record, then check the source.", ja: "選手データを探し、出典を確認する。", es: "Encontrá el registro y revisá su fuente." },
};
