import type { Player, Team } from "./types";

export const players: Player[] = [
  {
    id: "p-001",
    name: "Mateo Alvarez",
    age: 22,
    nationality: "Argentina",
    position: "MF",
    club: "River Norte",
    league: "Primera Sample",
    preferredFoot: "Right",
    heightCm: 176,
    marketValueEur: 2400000,
    contractUntil: "2028-06-30",
    appearances: 31,
    goals: 6,
    assists: 11,
    minutes: 2420,
    sourceUrl: "https://example.com/scoutboard/synthetic/player-p-001",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-20",
    researchNote:
      "Progressive central midfielder with clean receiving angles, high availability between lines, and reliable final-third passing.",
  },
  {
    id: "p-002",
    name: "Kenji Sato",
    age: 19,
    nationality: "Japan",
    position: "FW",
    club: "Yokohama Bays",
    league: "J Sample League",
    preferredFoot: "Left",
    heightCm: 181,
    marketValueEur: 1200000,
    contractUntil: "2027-01-31",
    appearances: 24,
    goals: 12,
    assists: 4,
    minutes: 1685,
    sourceUrl: "https://example.com/scoutboard/synthetic/player-p-002",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-21",
    researchNote:
      "Mobile forward who attacks the near post early and creates repeatable shots from inside the box.",
  },
  {
    id: "p-003",
    name: "Luca Weber",
    age: 28,
    nationality: "Germany",
    position: "DF",
    club: "Berlin Athletic",
    league: "Bundes Sample",
    preferredFoot: "Both",
    heightCm: 190,
    marketValueEur: 3600000,
    contractUntil: "2026-12-31",
    appearances: 29,
    goals: 2,
    assists: 1,
    minutes: 2610,
    sourceUrl: "https://example.com/scoutboard/synthetic/player-p-003",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-22",
    researchNote:
      "Dominant aerial centre-back with calm outlet passing and strong set-piece value.",
  },
  {
    id: "p-004",
    name: "Omar Diallo",
    age: 46,
    nationality: "",
    position: "AM",
    club: "Casablanca Port",
    league: "Atlantic Sample",
    preferredFoot: "Right",
    heightCm: 163,
    marketValueEur: -50000,
    contractUntil: "2021-06-30",
    appearances: 4,
    goals: 3,
    assists: 2,
    minutes: 0,
    sourceUrl: "",
    sourceName: "",
    lastCheckedAt: "",
    researchNote:
      "Intentional flawed record used to demonstrate validation and QA reporting.",
  },
];

export const teams: Team[] = [
  {
    id: "t-001",
    name: "River Norte",
    country: "Argentina",
    league: "Primera Sample",
    manager: "Santiago Paz",
    stadium: "Estadio del Norte",
    squadSize: 27,
    averageAge: 25.4,
    sourceUrl: "https://example.com/scoutboard/synthetic/team-t-001",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-20",
  },
  {
    id: "t-002",
    name: "Yokohama Bays",
    country: "Japan",
    league: "J Sample League",
    manager: "Hiro Tanaka",
    stadium: "Bay Field",
    squadSize: 29,
    averageAge: 24.1,
    sourceUrl: "https://example.com/scoutboard/synthetic/team-t-002",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-21",
  },
  {
    id: "t-003",
    name: "Berlin Athletic",
    country: "Germany",
    league: "Bundes Sample",
    manager: "Marta Klein",
    stadium: "Nordpark Arena",
    squadSize: 26,
    averageAge: 26.8,
    sourceUrl: "https://example.com/scoutboard/synthetic/team-t-003",
    sourceName: "ScoutBoard synthetic sample",
    lastCheckedAt: "2026-05-22",
  },
];
