import Link from "next/link";
import { loadAmericanWatchlist } from "@/lib/american-watchlist";
import { UI } from "@/app/components/ui-text";
import { T } from "@/app/components/language";
export default async function RosterReviewPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const rawParams = await searchParams;
  const params = Object.fromEntries(Object.entries(rawParams).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value]));
  const rows = await loadAmericanWatchlist(true);
  const status = ["confirmed", "unverified", "excluded"].includes(params.status ?? "") ? params.status! : "unverified";
  const search = (params.q ?? "").trim().toLowerCase();
  const filtered = rows.filter(p => p.review.status === status && (!search || `${p.name} ${p.club} ${p.league}`.toLowerCase().includes(search)));
  const pages = Math.max(1, Math.ceil(filtered.length / 40)); const page = Math.min(pages, Math.max(1, Math.floor(Number(params.page)) || 1));
  return <div className="pageStack toolPage"><div className="sectionHeader"><h1><UI text="Roster review" /></h1><p><T text={{en: "Every imported membership has a review state. A live Wikidata check filters historical records; named club-source evidence confirms a current membership.", ja: "取り込んだ所属情報ごとに確認状態を表示します。Wikidataで過去の情報を確認し、現在の所属はクラブの出典で確認します。", es: "Cada afiliación importada tiene un estado de revisión. Wikidata permite detectar registros históricos; una fuente del club confirma una afiliación actual."}} /></p></div><div className="toolBar">{(["confirmed", "unverified", "excluded"] as const).map(value => <Link key={value} href={{ query: { status: value } }}><UI text={value === "confirmed" ? "Confirmed memberships" : value === "excluded" ? "Excluded records" : "Unverified claims"} />: {rows.filter(p => p.review.status === value).length}</Link>)}</div><form className="toolBar"><label><UI text="Search" /><input name="q" defaultValue={params.q} /></label><input type="hidden" name="status" value={status} /><button><UI text="Apply" /></button></form><p>{filtered.length} · {page} / {pages}</p><div className="tableShell"><table><thead><tr><th><UI text="Player" /></th><th><UI text="Club" /></th><th><UI text="Reason" /></th><th><UI text="Review date" /></th><th><UI text="Review source" /></th></tr></thead><tbody>{filtered.slice((page - 1) * 40, page * 40).map(player => <tr key={player.id}><td>{player.name}</td><td>{player.club}</td><td><UI text={player.review.reason} /></td><td>{player.review.checkedAt ?? "—"}</td><td>{player.review.sourceUrl && <a href={player.review.sourceUrl} target="_blank" rel="noreferrer"><UI text="Review source" /></a>}{player.officialWebsite && <a className="block" href={player.officialWebsite} target="_blank" rel="noreferrer"><UI text="Official website" /></a>}</td></tr>)}</tbody></table></div><div className="toolBar">{page > 1 && <Link href={{ query: { ...params, page: page - 1 } }}><UI text="Previous" /></Link>}{page < pages && <Link href={{ query: { ...params, page: page + 1 } }}><UI text="Next" /></Link>}</div></div>;
}
